@startuml
[*] --> A
A --> B 
B --> C 

C --> D : Yes
C --> F : No

D --> E 
E --> I 

I --> F 
I --> H 

H --> D

F --> [*]

state "A New User Signs Up" as A
state "User Adds Personal Details" as B
state "User Decides to Setup Profile" as C
state "User Designs Music Persona" as D
state "User Previews Profile" as E
state "Complete User Profile" as I
state "User Revisits Design Interface" as H
state "Start Browsing" as F

@enduml