@startuml

package "Database" {

  class User {
    - UserID: str
    - Username: str
    - Email: str
    - Password: str
    - ProfilePicture: image
    - CreatedAt: str
    - Role: str
    + GetUserInfo()
    + UpdateUserInfo()
  }
  
  class Post {
    - PostID: str
    - UserID: str
    - ContentID: str
    - Caption: str
    - Likes: int
    - CreatedAT: str
    - Comments: list
    + GetPostInfo()
    + UpdatePostInfo()
  }
  
  class Like {
    - LikeID: str
    - UserID: str
    - PostID: str
    + GetLikeInfo()
    + UpdateLikeInfo()
  }
  
  class Comment{
    - CommentID: str
    - UserID: str
    - PostID: str
    - CreatedAT: str
    - Content: str
    + GetCommentInfo()
    + UpdateCommentInfo()
  }
  
  class Song{
    - SongID: str
    - SongName: str
    - Artist: str
    - Album: str
    - CoverURL: str
    - EmbedURL: str
    - SpotifyURL: str
    + GetSongInfo()
    + UpdateSongInfo()
  }
  
  class Album{
    - AlbumID: str
    - AlbumName: str
    - Artist: str
    - CoverURL: str
    - SpotifyURL: str
    + GetAlbumInfo()
    + UpdateAlbumInfo()
  }
  
  class Artist{
    - ArtistID: str
    - ArtistName: str
    - ArtistPictureURL: str
    - SpotifyURL: str
    + GetArtistInfo()
    + UpdateAlbumInfo()
  }
  
  class Profile{
    - ProfileID: str
    - UserID: str
    - ProfilePicture: image
    - FavoriteGenres: list
    - TopSongs: list
    - AlbumShowcase: list
    - ArtistShowcase: list
    - BadgeShowcase: list
    - ProfileBio: str
    - SongOTD: str
    - Posts: list
    + GetProfileInfo()
    + UpdateProfileInfo()
  }

  Profile "1" o-- "1" User
  Profile "1" *-- "*" Post
  Profile "1" o-- "*" Album
  Profile "1" o-- "*" Song
  Profile "1" o-- "*" Artist
  Post "1" *-- "*" Comment
  Post "1" *-- "*" Like
  Post "1" o-- "*" Song
  Post "1" o-- "*" Album
  Post "1" o-- "*" Artist
  User "1" *-- "*" Like
  User "1" *-- "*" Comment

}

package "Python"{

  package "SpotifyAPI" {
  
    class SpotifyAPI{
      - ClientID: str
      - ClientSecret: str
      - Token: str
      - GetToken()
      + Search(query(str), searchtype(str))
    }
    
    class SpotifySearch{
      - Spotify: SpotifyAPI
      - Query: str
      + GetTrack()
      + GetAlbum()
      + GetArtist()
    }
    
    class SearchRoute<<route>>{
    }
    
    SpotifyAPI "1" *-- "*" SpotifySearch
    SearchRoute "1" -- "*" SpotifySearch
  }
  
  package "OAuth"{
  
    class OAuth{
      - GoogleClientId: str
      - GoogleClientSecret: str
      - GoogleDiscoveryURL: str
      - UserID: str
      - Token: str
      - GetToken()
      + RequestLogin()
      + RedirectToGoogleLogin()
      + AccessTokens()
    }

    class LoginRoute<<route>> {
    }

    OAuth "1" *-- "*" LoginRoute
  }

  class Main<<file>>{
    + CreateApp()
  }
  
  class RegisterUser{
  }
}

package "JavaScript"{
  package "Profile"{
    class Profile {
      + render(): JSX.Element
    }
    
    class ProfileHeader {
      - ProfilePic: str
      - Username: str
      - Genres: list
    }
    
    class TopSongs {
      - Songs: list
    }
    
    class AlbumsShowcase {
      - Albums: list
    }
    
    class ArtistsShowcase {
      - Artists: list
    }
    
    class BadgesShowcase {
      - Badges: list
    }
    
    class Feed {
      - Posts: list
    }
    
    Profile "1" *-- "1" ProfileHeader
    Profile "1" *-- "*" TopSongs
    Profile "1" *-- "*" AlbumsShowcase
    Profile "1" *-- "*" ArtistsShowcase
    Profile "1" *-- "*" BadgesShowcase
    Profile "1" *-- "*" Feed
  }
}

@enduml
